### ISSUE TITLE
[Request] allow pokeball selection for pokemon not made legal through breeding

### ISSUE THREAD

**Issue by Snaid1** [Lorenzooone/Pokemon-Gen3-to-Gen-X#2]
while it seems most pokemon become legal by being hatched from an egg (and gen 3 breeding had all eggs in pokeballs) it would be nice if pokemon that had to be caught (like legendaries) could have their pokeball selected instead of always defaulting to pokeball. 
Given it's transfering from an older game, I could see limiting this to pokeball, great ball, ultra ball, and Master Ball.

**Comment by Lorenzooone** [comment]
Makes sense. It completely slipped my mind.
I am working on implementing an interface for it (I will need to move stuff around in the Settings menu).
Though, the program is converting to Gen 3, so any valid Gen 3 ball (sorry if you're a Safari Ball fan) will be allowed.

**Comment by Lorenzooone** [comment]
Implemented in the latest release. Let me know what you think!

**Comment by Lorenzooone** [comment]
Closing as completed...
