### ISSUE TITLE
Not working in emulator

### ISSUE THREAD

**Issue by KingDuckZ** [Lorenzooone/Pokemon-Gen3-to-Gen-X#4]
Hi, great job on this homebrew! Reading online, I found it should work with 2 GBAs, so I loaded this up in mGBA (which is the only emulator I know of that supports GBA-to-GBA link) but when I replace the ROM and press A to proceed the homebrew always fails to read data. Is it not possible to get this working?

**Comment by Lorenzooone** [comment]
Hello! If you wanted to check the homebrew working between Gen 1/2 and 3 on emulators, then it won't work (I know of no emulator which can allow that). It should be fine for Gen 3 to Gen 3.
Though you are correct that mgba does not properly load save data. It's an issue in the emulator itself, which I reported already. You can read more here: https://github.com/mgba-emu/mgba/issues/2864

**Comment by KingDuckZ** [comment]
Thanks for the quick reply! I thought mGBA would allow GBC-to-GBA, I must be mistaken :/ either way, since I can't get past the "Error reading the data!" error, in my case it won't work at all. I'll be waiting for mGBA to make a fix, although it's pointless if link to GBC mode window doesn't work.

**Comment by Lorenzooone** [comment]
I mean... You are free to try it... Though it's something related to the emulators themselves, not to the homebrew. Sorry, and best of luck! It may work and I'm simply mistaken...
