### ISSUE TITLE
UI Upgrade

### ISSUE THREAD

**Issue by Gronis** [Lorenzooone/Pokemon-Gen3-to-Gen-X#8]
Pokemon-Gen3-to-Gen-X is cramped with features for trading between GBA Pokemon generation 3 to GBC Pokemon generation 1-2. However, the UI is quite cramped and using it is very much a power user experience rather than something simplistic that follows the design language that pokemon games typically uses.

This issue tracks a UI upgrade job, with the following goals:

1. Introduce VWF (Variable Width Font) For easier readability and ability to fit more text on screen.
2. Make UI more user friendly and less intimidating for non-power users.
3. Don't remove features for the power users.

**Comment by Gronis** [comment]
This is the current designs for the `Main Menu` and a new `Trade Menu` (not implemented in code, just a sketch for now)

## Main Menu
![ui_main_menu](https://github.com/Lorenzooone/Pokemon-Gen3-to-Gen-X/assets/5390421/708cad7e-fdeb-4e2b-8aa2-b63b7d7c46ff)

## Trade Menu
![ui_trade_menu](https://github.com/Lorenzooone/Pokemon-Gen3-to-Gen-X/assets/5390421/747bec35-6571-462a-af37-d7396d8b9fc6)

Feedback is welcomed

**Comment by Lorenzooone** [comment]
Sounds like a good plan to me, though it's improtant that it's done in the proper order (so the UI changes must come after the VWF, otherwise it would be a pain).

From a design standpoint, I don't really like "View Party" being inside the Trade menu. It can be used for certain features. Though maybe a good approach to that would be a "Regular" menu accessible in the main menu, and the "Gen-specific" one inside the Trade Menu.

**Comment by Gronis** [comment]
Good points. Yea, It has to be done in steps.

I later realised that View Party is hidden inside Trade Menu is less than ideal. I like your suggestion that puts Party on both menus, where the first is always the Gen 3 version, and in the trade menu, it's converted into the generation to trade with.

**Comment by Gronis** [comment]
I will close this as there is an alternative application for people that want something that is more UI friendly. Pokemon gen 3 to gen x is somewhat of a power user app so it's fine if its less polished UI wise.
